### PR TITLE
917 - Fix filtering in the project samples table

### LINKED ISSUE #917: Fix filtering in the project samples table
### Context

We've found two types of bugs in the project samples table that impact the user experience. Specifically, filtering by user-entered keyword strings (partially) and filtering by sample IDs are both not functioning as intended.

e.g. ) By user-entered keyword strings:

bug-by-user-entered-terms

e.g. ) By sample IDs:

bug-by-sampe-ids

### Problem or idea

We should resolve these filtering bugs so that users can filter the samples table data by terms or sample IDs as expected.

### Solution or next step

1. Fix the filtering bug for string keywords
2. Fix the filtering bug for sample IDs

### PR DESCRIPTION
**Pull request by nozomione**
## Issue Number

Closes #917

## Purpose/Implementation Notes
Fixed filtering bugs in the following components:
- `Table`
- `ProjectSamplesTable`

## Types of changes
- Bugfix (non-breaking change which fixes an issue)

## Functional tests
N/A

## Checklist

- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Screenshots
N/A

### CODE REVIEW

File: client/src/components/Table.js [hunk 1]
```diff
@@ -233,7 +231,7 @@ export const Table = ({
     {
       columns,
       data,
-      globalFilter,
+      defaultFilter: 'fuzzyText', // Set default to fuzzyText
```
Comment (davidsmejia) [inline client/src/components/Table.js:234]:
```suggestion
      defaultFilter: 'fuzzyText',
```

**Review by davidsmejia — APPROVED** [review]
LGTM
